// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeun.Web.Data;

#nullable disable

namespace Zeun.Web.Migrations
{
    [DbContext(typeof(OgrenciDbContext))]
    partial class OgrenciDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeun.Web.Models.AkademikDonem", b =>
                {
                    b.Property<int>("AkademikDonemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AkademikDonemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AkademikDonemId"));

                    b.Property<string>("AkademikDonem1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AkademikDonem");

                    b.HasKey("AkademikDonemId");

                    b.ToTable("AkademikDonem", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.AkademikYil", b =>
                {
                    b.Property<int>("AkademikYilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AkademikYilID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AkademikYilId"));

                    b.Property<string>("AkademikYil1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AkademikYil");

                    b.HasKey("AkademikYilId");

                    b.ToTable("AkademikYil", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BolumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumId"));

                    b.Property<string>("BolumAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BolumFakulteId")
                        .HasColumnType("int")
                        .HasColumnName("BolumFakulteID");

                    b.Property<int?>("OgrenimDiliId")
                        .HasColumnType("int")
                        .HasColumnName("OgrenimDiliID");

                    b.Property<int?>("OgretimTuruId")
                        .HasColumnType("int")
                        .HasColumnName("OgretimTuruID");

                    b.Property<int?>("ProgramTuruId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramTuruID");

                    b.Property<string>("WebAdresi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BolumId");

                    b.HasIndex("BolumFakulteId");

                    b.HasIndex("OgrenimDiliId");

                    b.HasIndex("OgretimTuruId");

                    b.HasIndex("ProgramTuruId");

                    b.ToTable("Bolum", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Cinsiyet", b =>
                {
                    b.Property<int>("CinsiyetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CinsiyetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinsiyetId"));

                    b.Property<string>("CinsiyetAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CinsiyetId");

                    b.ToTable("Cinsiyet", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Danismanlik", b =>
                {
                    b.Property<int>("DanismanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DanismanlikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanismanlikId"));

                    b.Property<int?>("OgrElmId")
                        .HasColumnType("int")
                        .HasColumnName("OgrElmID");

                    b.Property<int?>("OgrenciId")
                        .HasColumnType("int")
                        .HasColumnName("OgrenciID");

                    b.HasKey("DanismanlikId");

                    b.HasIndex("OgrElmId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Danismanlik", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Degerlendirme", b =>
                {
                    b.Property<int>("DegerlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DegerlendirmeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegerlendirmeId"));

                    b.Property<int?>("OgrenciId")
                        .HasColumnType("int")
                        .HasColumnName("OgrenciID");

                    b.Property<int?>("SinavId")
                        .HasColumnType("int")
                        .HasColumnName("SinavID");

                    b.Property<float?>("SinavNotu")
                        .HasColumnType("real");

                    b.HasKey("DegerlendirmeId");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("SinavId");

                    b.ToTable("Degerlendirme", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAcma", b =>
                {
                    b.Property<int>("DersAcmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersAcmaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersAcmaId"));

                    b.Property<int?>("AkademikDonemId")
                        .HasColumnType("int")
                        .HasColumnName("AkademikDonemID");

                    b.Property<int?>("AkademikYilId")
                        .HasColumnType("int")
                        .HasColumnName("AkademikYilID");

                    b.Property<int?>("Kontejan")
                        .HasColumnType("int");

                    b.Property<int?>("MufredatId")
                        .HasColumnType("int")
                        .HasColumnName("MufredatID");

                    b.Property<int?>("OgrElmId")
                        .HasColumnType("int")
                        .HasColumnName("OgrElmID");

                    b.HasKey("DersAcmaId");

                    b.HasIndex("AkademikDonemId");

                    b.HasIndex("AkademikYilId");

                    b.HasIndex("MufredatId");

                    b.HasIndex("OgrElmId");

                    b.ToTable("DersAcma", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAlma", b =>
                {
                    b.Property<int>("DersAlmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersAlmaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersAlmaId"));

                    b.Property<int?>("DersAcmaId")
                        .HasColumnType("int")
                        .HasColumnName("DersAcmaID");

                    b.Property<int?>("DersAlmaDurumId")
                        .HasColumnType("int")
                        .HasColumnName("DersAlmaDurumID");

                    b.Property<int?>("OgrenciId")
                        .HasColumnType("int")
                        .HasColumnName("OgrenciID");

                    b.HasKey("DersAlmaId");

                    b.HasIndex("DersAcmaId");

                    b.HasIndex("DersAlmaDurumId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("DersAlma", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAlmaDurumu", b =>
                {
                    b.Property<int>("DersAlmaDurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersAlmaDurumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersAlmaDurumId"));

                    b.Property<string>("DersAlmaDurumu1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersAlmaDurumu");

                    b.HasKey("DersAlmaDurumId");

                    b.ToTable("DersAlmaDurumu", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersDili", b =>
                {
                    b.Property<int>("DersDiliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersDiliID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersDiliId"));

                    b.Property<string>("DersDili1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersDili");

                    b.HasKey("DersDiliId");

                    b.ToTable("DersDili", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersGunu", b =>
                {
                    b.Property<int>("DersGunuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersGunuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersGunuId"));

                    b.Property<string>("DersGunu1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersGunu");

                    b.HasKey("DersGunuId");

                    b.ToTable("DersGunu", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersHavuzu", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("DersAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DersAlmaId")
                        .HasColumnType("int");

                    b.Property<int?>("DersDiliId")
                        .HasColumnType("int")
                        .HasColumnName("DersDiliID");

                    b.Property<string>("DersKodu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DersSeviyesiId")
                        .HasColumnType("int")
                        .HasColumnName("DersSeviyesiID");

                    b.Property<int?>("DersTuruId")
                        .HasColumnType("int")
                        .HasColumnName("DersTuruID");

                    b.Property<int?>("Ects")
                        .HasColumnType("int")
                        .HasColumnName("ECTS");

                    b.Property<float?>("Kredi")
                        .HasColumnType("real");

                    b.Property<int?>("Teorik")
                        .HasColumnType("int");

                    b.Property<int?>("Uygulama")
                        .HasColumnType("int");

                    b.HasKey("DersId");

                    b.HasIndex("DersAlmaId");

                    b.HasIndex("DersDiliId");

                    b.HasIndex("DersSeviyesiId");

                    b.HasIndex("DersTuruId");

                    b.ToTable("DersHavuzu", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersProgrami", b =>
                {
                    b.Property<int>("DersProgramiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersProgramiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersProgramiId"));

                    b.Property<int?>("DersAcmaId")
                        .HasColumnType("int")
                        .HasColumnName("DersAcmaID");

                    b.Property<int?>("DersGunuId")
                        .HasColumnType("int")
                        .HasColumnName("DersGunuID");

                    b.Property<int?>("DersSaatiId")
                        .HasColumnType("int")
                        .HasColumnName("DersSaatiID");

                    b.Property<int?>("DerslikId")
                        .HasColumnType("int")
                        .HasColumnName("DerslikID");

                    b.HasKey("DersProgramiId");

                    b.HasIndex("DersAcmaId");

                    b.HasIndex("DersGunuId");

                    b.HasIndex("DersSaatiId");

                    b.HasIndex("DerslikId");

                    b.ToTable("DersProgrami", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersSaati", b =>
                {
                    b.Property<int>("DersSaatiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersSaatiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersSaatiId"));

                    b.Property<string>("DersSaati1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersSaati");

                    b.HasKey("DersSaatiId");

                    b.ToTable("DersSaati", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersSeviyesi", b =>
                {
                    b.Property<int>("DersSeviyesiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersSeviyesiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersSeviyesiId"));

                    b.Property<string>("DersSeviyesi1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersSeviyesi");

                    b.HasKey("DersSeviyesiId");

                    b.ToTable("DersSeviyesi", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DersTuru", b =>
                {
                    b.Property<int>("DersTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DersTuruID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersTuruId"));

                    b.Property<string>("DersTuru1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DersTuru");

                    b.HasKey("DersTuruId");

                    b.ToTable("DersTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Derslik", b =>
                {
                    b.Property<int>("DerslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DerslikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DerslikId"));

                    b.Property<string>("DerslikAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DerslikTuruId")
                        .HasColumnType("int")
                        .HasColumnName("DerslikTuruID");

                    b.Property<int?>("Kapasite")
                        .HasColumnType("int");

                    b.HasKey("DerslikId");

                    b.HasIndex("DerslikTuruId");

                    b.ToTable("Derslik", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.DerslikTuru", b =>
                {
                    b.Property<int>("DerslikTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DerslikTuruID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DerslikTuruId"));

                    b.Property<string>("DerslikTuruAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DerslikTuruId");

                    b.ToTable("DerslikTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Fakulte", b =>
                {
                    b.Property<int>("FakulteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FakulteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FakulteId"));

                    b.Property<string>("FakulteAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("FakulteId");

                    b.ToTable("Fakulte", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KullaniciTuruId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciTuruID");

                    b.Property<string>("Parola")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("KullaniciTuruId");

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.KullaniciTuru", b =>
                {
                    b.Property<int>("KullaniciTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciTurID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciTurId"));

                    b.Property<string>("KullaniciTurAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciTurId");

                    b.ToTable("KullaniciTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Mufredat", b =>
                {
                    b.Property<int>("MufredatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MufredatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MufredatId"));

                    b.Property<int?>("AkademikDonemId")
                        .HasColumnType("int")
                        .HasColumnName("AkademikDonemID");

                    b.Property<int?>("AkademikYiIid")
                        .HasColumnType("int")
                        .HasColumnName("AkademikYiIID");

                    b.Property<int?>("BolumId")
                        .HasColumnType("int")
                        .HasColumnName("BolumID");

                    b.Property<int?>("DersDonemi")
                        .HasColumnType("int");

                    b.Property<int?>("DersId")
                        .HasColumnType("int")
                        .HasColumnName("DersID");

                    b.HasKey("MufredatId");

                    b.HasIndex("AkademikDonemId");

                    b.HasIndex("AkademikYiIid");

                    b.HasIndex("BolumId");

                    b.HasIndex("DersId");

                    b.ToTable("Mufredat", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OgrenciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<string>("Adi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("AyrilmaTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("BolumId")
                        .HasColumnType("int")
                        .HasColumnName("BolumID");

                    b.Property<int?>("CinsiyetId")
                        .HasColumnType("int")
                        .HasColumnName("CinsiyetID");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gano")
                        .HasColumnType("float")
                        .HasColumnName("GANO");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<int?>("OgrenciDurumId")
                        .HasColumnType("int")
                        .HasColumnName("OgrenciDurumID");

                    b.Property<string>("OgrenciNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TckimlikNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TCKimlikNo");

                    b.Property<string>("TelefonNumarasi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OgrenciDurumId");

                    b.ToTable("Ogrenci", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.OgrenciDurum", b =>
                {
                    b.Property<int>("OgrenciDurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OgrenciDurumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciDurumId"));

                    b.Property<string>("OgrenciDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OgrenciDurumId");

                    b.ToTable("OgrenciDurum", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.OgrenimDili", b =>
                {
                    b.Property<int>("OgrenimDiliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OgrenimDiliID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenimDiliId"));

                    b.Property<string>("OgrenimDili1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OgrenimDili");

                    b.HasKey("OgrenimDiliId");

                    b.ToTable("OgrenimDili", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.OgretimElemani", b =>
                {
                    b.Property<int>("OgretimElemaniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OgretimElemaniID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretimElemaniId"));

                    b.Property<string>("Adi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("BolumId")
                        .HasColumnType("int")
                        .HasColumnName("BolumID");

                    b.Property<int?>("CinsiyetId")
                        .HasColumnType("int")
                        .HasColumnName("CinsiyetID");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<string>("KurumSicilNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TckimlikNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TCKimlikNo");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnvanId")
                        .HasColumnType("int")
                        .HasColumnName("UnvanID");

                    b.HasKey("OgretimElemaniId");

                    b.HasIndex("BolumId");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UnvanId");

                    b.ToTable("OgretimElemani", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.OgretimTuru", b =>
                {
                    b.Property<int>("OgretimTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OgretimTuruID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretimTuruId"));

                    b.Property<string>("OgretimTurAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OgretimTuruId");

                    b.ToTable("OgretimTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.ProgramTuru", b =>
                {
                    b.Property<int>("ProgramTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgramTuruID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramTuruId"));

                    b.Property<string>("ProgramTurAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProgramTuruId");

                    b.ToTable("ProgramTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Sinav", b =>
                {
                    b.Property<int>("SinavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SinavID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavId"));

                    b.Property<int?>("DersAcmaId")
                        .HasColumnType("int")
                        .HasColumnName("DersAcmaID");

                    b.Property<int?>("DerslikId")
                        .HasColumnType("int")
                        .HasColumnName("DerslikID");

                    b.Property<int?>("EtkiOrani")
                        .HasColumnType("int");

                    b.Property<int?>("OgrElmId")
                        .HasColumnType("int")
                        .HasColumnName("OgrElmID");

                    b.Property<DateTime?>("SinavSaati")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SinavTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("SinavTuruId")
                        .HasColumnType("int")
                        .HasColumnName("SinavTuruID");

                    b.HasKey("SinavId");

                    b.HasIndex("DersAcmaId");

                    b.HasIndex("DerslikId");

                    b.HasIndex("OgrElmId");

                    b.HasIndex("SinavTuruId");

                    b.ToTable("Sinav", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.SinavTuru", b =>
                {
                    b.Property<int>("SinavTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SinavTuruID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavTuruId"));

                    b.Property<string>("SinavTuru1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SinavTuru");

                    b.HasKey("SinavTuruId");

                    b.ToTable("SinavTuru", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Unvan", b =>
                {
                    b.Property<int>("UnvanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnvanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanId"));

                    b.Property<string>("UnvanAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnvanId");

                    b.ToTable("Unvan", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Yandal", b =>
                {
                    b.Property<int>("YandalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YandalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YandalId"));

                    b.Property<int>("YandalBolumId")
                        .HasColumnType("int")
                        .HasColumnName("YandalBolumID");

                    b.Property<int>("YandalOgrenciId")
                        .HasColumnType("int")
                        .HasColumnName("YandalOgrenciID");

                    b.HasKey("YandalId");

                    b.HasIndex("YandalBolumId");

                    b.ToTable("Yandal", (string)null);
                });

            modelBuilder.Entity("Zeun.Web.Models.Bolum", b =>
                {
                    b.HasOne("Zeun.Web.Models.Fakulte", "BolumFakulte")
                        .WithMany("Bolums")
                        .HasForeignKey("BolumFakulteId")
                        .HasConstraintName("FK_Bolum_Fakulte");

                    b.HasOne("Zeun.Web.Models.OgrenimDili", "OgrenimDili")
                        .WithMany("Bolums")
                        .HasForeignKey("OgrenimDiliId")
                        .HasConstraintName("FK_Bolum_OgrenimDili");

                    b.HasOne("Zeun.Web.Models.OgretimTuru", "OgretimTuru")
                        .WithMany("Bolums")
                        .HasForeignKey("OgretimTuruId")
                        .HasConstraintName("FK_Bolum_OgretimTuru");

                    b.HasOne("Zeun.Web.Models.ProgramTuru", "ProgramTuru")
                        .WithMany("Bolums")
                        .HasForeignKey("ProgramTuruId")
                        .HasConstraintName("FK_Bolum_ProgramTuru");

                    b.Navigation("BolumFakulte");

                    b.Navigation("OgrenimDili");

                    b.Navigation("OgretimTuru");

                    b.Navigation("ProgramTuru");
                });

            modelBuilder.Entity("Zeun.Web.Models.Danismanlik", b =>
                {
                    b.HasOne("Zeun.Web.Models.OgretimElemani", "OgrElm")
                        .WithMany("Danismanliks")
                        .HasForeignKey("OgrElmId")
                        .HasConstraintName("FK_Danismanlik_OgretimElemani");

                    b.HasOne("Zeun.Web.Models.Ogrenci", "Ogrenci")
                        .WithMany("Danismanliks")
                        .HasForeignKey("OgrenciId")
                        .HasConstraintName("FK_Danismanlik_Ogrenci");

                    b.Navigation("OgrElm");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Zeun.Web.Models.Degerlendirme", b =>
                {
                    b.HasOne("Zeun.Web.Models.Ogrenci", "Ogrenci")
                        .WithMany("Degerlendirmes")
                        .HasForeignKey("OgrenciId")
                        .HasConstraintName("FK_Degerlendirme_Ogrenci");

                    b.HasOne("Zeun.Web.Models.Sinav", "Sinav")
                        .WithMany("Degerlendirmes")
                        .HasForeignKey("SinavId")
                        .HasConstraintName("FK_Degerlendirme_Sinav");

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAcma", b =>
                {
                    b.HasOne("Zeun.Web.Models.AkademikDonem", "AkademikDonem")
                        .WithMany("DersAcmas")
                        .HasForeignKey("AkademikDonemId")
                        .HasConstraintName("FK_DersAcma_AkademikDonem");

                    b.HasOne("Zeun.Web.Models.AkademikYil", "AkademikYil")
                        .WithMany("DersAcmas")
                        .HasForeignKey("AkademikYilId")
                        .HasConstraintName("FK_DersAcma_AkademikYil");

                    b.HasOne("Zeun.Web.Models.Mufredat", "Mufredat")
                        .WithMany("DersAcmas")
                        .HasForeignKey("MufredatId")
                        .HasConstraintName("FK_DersAcma_Mufredat");

                    b.HasOne("Zeun.Web.Models.OgretimElemani", "OgrElm")
                        .WithMany("DersAcmas")
                        .HasForeignKey("OgrElmId")
                        .HasConstraintName("FK_DersAcma_OgretimElemani");

                    b.Navigation("AkademikDonem");

                    b.Navigation("AkademikYil");

                    b.Navigation("Mufredat");

                    b.Navigation("OgrElm");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAlma", b =>
                {
                    b.HasOne("Zeun.Web.Models.DersAcma", "DersAcma")
                        .WithMany("DersAlmas")
                        .HasForeignKey("DersAcmaId")
                        .HasConstraintName("FK_DersAlma_DersAcma");

                    b.HasOne("Zeun.Web.Models.DersAlmaDurumu", "DersAlmaDurum")
                        .WithMany("DersAlmas")
                        .HasForeignKey("DersAlmaDurumId")
                        .HasConstraintName("FK_DersAlma_DersAlmaDurumu");

                    b.HasOne("Zeun.Web.Models.Ogrenci", "Ogrenci")
                        .WithMany("DersAlmas")
                        .HasForeignKey("OgrenciId")
                        .HasConstraintName("FK_DersAlma_Ogrenci");

                    b.Navigation("DersAcma");

                    b.Navigation("DersAlmaDurum");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersHavuzu", b =>
                {
                    b.HasOne("Zeun.Web.Models.DersAlma", null)
                        .WithMany("DersHavuzu")
                        .HasForeignKey("DersAlmaId");

                    b.HasOne("Zeun.Web.Models.DersDili", "DersDili")
                        .WithMany("DersHavuzus")
                        .HasForeignKey("DersDiliId")
                        .HasConstraintName("FK_DersHavuzu_DersDili");

                    b.HasOne("Zeun.Web.Models.DersSeviyesi", "DersSeviyesi")
                        .WithMany("DersHavuzus")
                        .HasForeignKey("DersSeviyesiId")
                        .HasConstraintName("FK_DersHavuzu_DersSeviyesi");

                    b.HasOne("Zeun.Web.Models.DerslikTuru", "DersTuru")
                        .WithMany("DersHavuzus")
                        .HasForeignKey("DersTuruId")
                        .HasConstraintName("FK_DersHavuzu_DerslikTuru");

                    b.Navigation("DersDili");

                    b.Navigation("DersSeviyesi");

                    b.Navigation("DersTuru");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersProgrami", b =>
                {
                    b.HasOne("Zeun.Web.Models.DersAcma", "DersAcma")
                        .WithMany("DersProgramis")
                        .HasForeignKey("DersAcmaId")
                        .HasConstraintName("FK_DersProgrami_DersAcma");

                    b.HasOne("Zeun.Web.Models.DersGunu", "DersGunu")
                        .WithMany("DersProgramis")
                        .HasForeignKey("DersGunuId")
                        .HasConstraintName("FK_DersProgrami_DersGunu");

                    b.HasOne("Zeun.Web.Models.DersSaati", "DersSaati")
                        .WithMany("DersProgramis")
                        .HasForeignKey("DersSaatiId")
                        .HasConstraintName("FK_DersProgrami_DersSaati");

                    b.HasOne("Zeun.Web.Models.Derslik", "Derslik")
                        .WithMany("DersProgramis")
                        .HasForeignKey("DerslikId")
                        .HasConstraintName("FK_DersProgrami_Derslik");

                    b.Navigation("DersAcma");

                    b.Navigation("DersGunu");

                    b.Navigation("DersSaati");

                    b.Navigation("Derslik");
                });

            modelBuilder.Entity("Zeun.Web.Models.Derslik", b =>
                {
                    b.HasOne("Zeun.Web.Models.DerslikTuru", "DerslikTuru")
                        .WithMany("Dersliks")
                        .HasForeignKey("DerslikTuruId")
                        .HasConstraintName("FK_Derslik_DerslikTuru");

                    b.Navigation("DerslikTuru");
                });

            modelBuilder.Entity("Zeun.Web.Models.Kullanici", b =>
                {
                    b.HasOne("Zeun.Web.Models.KullaniciTuru", "KullaniciTuru")
                        .WithMany("Kullanicis")
                        .HasForeignKey("KullaniciTuruId")
                        .HasConstraintName("FK_Kullanici_KullaniciTuru");

                    b.Navigation("KullaniciTuru");
                });

            modelBuilder.Entity("Zeun.Web.Models.Mufredat", b =>
                {
                    b.HasOne("Zeun.Web.Models.AkademikDonem", "AkademikDonem")
                        .WithMany("Mufredats")
                        .HasForeignKey("AkademikDonemId")
                        .HasConstraintName("FK_Mufredat_AkademikDonem");

                    b.HasOne("Zeun.Web.Models.AkademikYil", "AkademikYiI")
                        .WithMany("Mufredats")
                        .HasForeignKey("AkademikYiIid")
                        .HasConstraintName("FK_Mufredat_AkademikYil");

                    b.HasOne("Zeun.Web.Models.Bolum", "Bolum")
                        .WithMany("Mufredats")
                        .HasForeignKey("BolumId")
                        .HasConstraintName("FK_Mufredat_Bolum");

                    b.HasOne("Zeun.Web.Models.DersHavuzu", "Ders")
                        .WithMany("Mufredats")
                        .HasForeignKey("DersId")
                        .HasConstraintName("FK_Mufredat_DersHavuzu");

                    b.Navigation("AkademikDonem");

                    b.Navigation("AkademikYiI");

                    b.Navigation("Bolum");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Zeun.Web.Models.Ogrenci", b =>
                {
                    b.HasOne("Zeun.Web.Models.Bolum", "Bolum")
                        .WithMany("Ogrencis")
                        .HasForeignKey("BolumId")
                        .HasConstraintName("FK_Ogrenci_Bolum");

                    b.HasOne("Zeun.Web.Models.Cinsiyet", "Cinsiyet")
                        .WithMany("Ogrencis")
                        .HasForeignKey("CinsiyetId")
                        .HasConstraintName("FK_Ogrenci_Cinsiyet");

                    b.HasOne("Zeun.Web.Models.Kullanici", "Kullanici")
                        .WithMany("Ogrencis")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK_Ogrenci_Kullanici");

                    b.HasOne("Zeun.Web.Models.OgrenciDurum", "OgrenciDurum")
                        .WithMany("Ogrencis")
                        .HasForeignKey("OgrenciDurumId")
                        .HasConstraintName("FK_Ogrenci_OgrenciDurum");

                    b.Navigation("Bolum");

                    b.Navigation("Cinsiyet");

                    b.Navigation("Kullanici");

                    b.Navigation("OgrenciDurum");
                });

            modelBuilder.Entity("Zeun.Web.Models.OgretimElemani", b =>
                {
                    b.HasOne("Zeun.Web.Models.Bolum", "Bolum")
                        .WithMany("OgretimElemanis")
                        .HasForeignKey("BolumId")
                        .HasConstraintName("FK_OgretimElemani_Bolum");

                    b.HasOne("Zeun.Web.Models.Cinsiyet", "Cinsiyet")
                        .WithMany("OgretimElemanis")
                        .HasForeignKey("CinsiyetId")
                        .HasConstraintName("FK_OgretimElemani_Cinsiyet");

                    b.HasOne("Zeun.Web.Models.Kullanici", "Kullanici")
                        .WithMany("OgretimElemanis")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK_OgretimElemani_Kullanici");

                    b.HasOne("Zeun.Web.Models.Unvan", "Unvan")
                        .WithMany("OgretimElemanis")
                        .HasForeignKey("UnvanId")
                        .HasConstraintName("FK_OgretimElemani_Unvan");

                    b.Navigation("Bolum");

                    b.Navigation("Cinsiyet");

                    b.Navigation("Kullanici");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("Zeun.Web.Models.Sinav", b =>
                {
                    b.HasOne("Zeun.Web.Models.DersAcma", "DersAcma")
                        .WithMany("Sinavs")
                        .HasForeignKey("DersAcmaId")
                        .HasConstraintName("FK_Sinav_DersAcma");

                    b.HasOne("Zeun.Web.Models.Derslik", "Derslik")
                        .WithMany("Sinavs")
                        .HasForeignKey("DerslikId")
                        .HasConstraintName("FK_Sinav_Derslik");

                    b.HasOne("Zeun.Web.Models.OgretimElemani", "OgrElm")
                        .WithMany("Sinavs")
                        .HasForeignKey("OgrElmId")
                        .HasConstraintName("FK_Sinav_OgretimElemani");

                    b.HasOne("Zeun.Web.Models.SinavTuru", "SinavTuru")
                        .WithMany("Sinavs")
                        .HasForeignKey("SinavTuruId")
                        .HasConstraintName("FK_Sinav_SinavTuru");

                    b.Navigation("DersAcma");

                    b.Navigation("Derslik");

                    b.Navigation("OgrElm");

                    b.Navigation("SinavTuru");
                });

            modelBuilder.Entity("Zeun.Web.Models.Yandal", b =>
                {
                    b.HasOne("Zeun.Web.Models.Bolum", "YandalBolum")
                        .WithMany("Yandals")
                        .HasForeignKey("YandalBolumId")
                        .IsRequired()
                        .HasConstraintName("FK_Yandal_Bolum");

                    b.Navigation("YandalBolum");
                });

            modelBuilder.Entity("Zeun.Web.Models.AkademikDonem", b =>
                {
                    b.Navigation("DersAcmas");

                    b.Navigation("Mufredats");
                });

            modelBuilder.Entity("Zeun.Web.Models.AkademikYil", b =>
                {
                    b.Navigation("DersAcmas");

                    b.Navigation("Mufredats");
                });

            modelBuilder.Entity("Zeun.Web.Models.Bolum", b =>
                {
                    b.Navigation("Mufredats");

                    b.Navigation("Ogrencis");

                    b.Navigation("OgretimElemanis");

                    b.Navigation("Yandals");
                });

            modelBuilder.Entity("Zeun.Web.Models.Cinsiyet", b =>
                {
                    b.Navigation("Ogrencis");

                    b.Navigation("OgretimElemanis");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAcma", b =>
                {
                    b.Navigation("DersAlmas");

                    b.Navigation("DersProgramis");

                    b.Navigation("Sinavs");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAlma", b =>
                {
                    b.Navigation("DersHavuzu");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersAlmaDurumu", b =>
                {
                    b.Navigation("DersAlmas");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersDili", b =>
                {
                    b.Navigation("DersHavuzus");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersGunu", b =>
                {
                    b.Navigation("DersProgramis");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersHavuzu", b =>
                {
                    b.Navigation("Mufredats");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersSaati", b =>
                {
                    b.Navigation("DersProgramis");
                });

            modelBuilder.Entity("Zeun.Web.Models.DersSeviyesi", b =>
                {
                    b.Navigation("DersHavuzus");
                });

            modelBuilder.Entity("Zeun.Web.Models.Derslik", b =>
                {
                    b.Navigation("DersProgramis");

                    b.Navigation("Sinavs");
                });

            modelBuilder.Entity("Zeun.Web.Models.DerslikTuru", b =>
                {
                    b.Navigation("DersHavuzus");

                    b.Navigation("Dersliks");
                });

            modelBuilder.Entity("Zeun.Web.Models.Fakulte", b =>
                {
                    b.Navigation("Bolums");
                });

            modelBuilder.Entity("Zeun.Web.Models.Kullanici", b =>
                {
                    b.Navigation("Ogrencis");

                    b.Navigation("OgretimElemanis");
                });

            modelBuilder.Entity("Zeun.Web.Models.KullaniciTuru", b =>
                {
                    b.Navigation("Kullanicis");
                });

            modelBuilder.Entity("Zeun.Web.Models.Mufredat", b =>
                {
                    b.Navigation("DersAcmas");
                });

            modelBuilder.Entity("Zeun.Web.Models.Ogrenci", b =>
                {
                    b.Navigation("Danismanliks");

                    b.Navigation("Degerlendirmes");

                    b.Navigation("DersAlmas");
                });

            modelBuilder.Entity("Zeun.Web.Models.OgrenciDurum", b =>
                {
                    b.Navigation("Ogrencis");
                });

            modelBuilder.Entity("Zeun.Web.Models.OgrenimDili", b =>
                {
                    b.Navigation("Bolums");
                });

            modelBuilder.Entity("Zeun.Web.Models.OgretimElemani", b =>
                {
                    b.Navigation("Danismanliks");

                    b.Navigation("DersAcmas");

                    b.Navigation("Sinavs");
                });

            modelBuilder.Entity("Zeun.Web.Models.OgretimTuru", b =>
                {
                    b.Navigation("Bolums");
                });

            modelBuilder.Entity("Zeun.Web.Models.ProgramTuru", b =>
                {
                    b.Navigation("Bolums");
                });

            modelBuilder.Entity("Zeun.Web.Models.Sinav", b =>
                {
                    b.Navigation("Degerlendirmes");
                });

            modelBuilder.Entity("Zeun.Web.Models.SinavTuru", b =>
                {
                    b.Navigation("Sinavs");
                });

            modelBuilder.Entity("Zeun.Web.Models.Unvan", b =>
                {
                    b.Navigation("OgretimElemanis");
                });
#pragma warning restore 612, 618
        }
    }
}
